---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Install Collectd RPM package
  yum:
    name: "{{ collectd_pkg }}"
    state: present
  notify:
    - Restart collectd service
  tags:
    - collectd_pkg

- name: Install additional Collectd plugin RPM package
  yum:
    name: "{{ item }}"
    state: present
  with_items: collectd_pkg_plugins
  notify:
    - Restart collectd service
  tags:
    - collectd_pkg

- name: Configure CollectD
  template:
    src: collectd.conf.j2
    dest: "{{ collectd_config_path }}"
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Make sure collectd service is enabled and running
  service:
    name: collectd
    enabled: yes
    state: running

- name: Configure custom types.db
  template:
    src: types.db.j2
    dest: "{{ collectd_global_options_default_typesdb_custom }}"
  when: >
    collectd_global_options_default_typesdb_custom and
    collectd_types
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Remove custom types.db file
  file:
    path: "{{ collectd_global_options_default_typesdb_custom }}"
    state: absent
  when: >
    collectd_global_options_default_typesdb_custom and
    not collectd_types
  notify:
    - Restart collectd service
  tags:
    - collectd_config
